F13 Página de visualização de reward
fga-eps-mds/2019.1-PretEvent pull request #135
Opened 2019-05-11 19:54 UTC by murilo-dan

F13 - [FEATURE] - Página de visualização de reward #68 

## Descrição
Adição da visualização de recompensa.

## Porque este Pull Request é necessário?
Permite a visualização das recompensas já criadas.

## Critérios
- [x] Mostrar todos os dados de reward

Resolve #68 .

2019-05-11 20:52 UTC, djorkaeffalexandre commented on front-end/pret-event/src/app/screens/see-reward/see-reward.component.ts
> +  detectFiles(event) {
Função não utilizada.

2019-05-11 20:53 UTC, djorkaeffalexandre commented on front-end/pret-event/src/app/screens/see-reward/see-reward.component.ts
> +  file: any;
Variável não está sendo utilizada para nada.

2019-05-11 20:54 UTC, djorkaeffalexandre commented
@murilo-dan corrija os problemas apontados, código não utilizado não deve estar nos Arquivos, dê atenção a isso.

2019-05-11 20:54 UTC, djorkaeffalexandre requested changes

2019-05-11 20:54 UTC, djorkaeffalexandre commented on front-end/pret-event/src/app/screens/see-reward/see-reward.component.ts
> +  valid = true;
Variável não utilizada.

2019-05-13 12:13 UTC, gustavocarvalho1002 commented
@murilo-dan atentar as correções necessárias para a aceitação de PR

2019-05-13 13:05 UTC, murilo-dan commented
As correções  requisitadas foram feitas, aguardando aprovação do PR ou requisição de novas mudanças.

2019-05-16 19:18 UTC, murilo-dan commented
Build passando, aguardando _review_.

2019-05-18 00:54 UTC, gustavocarvalho1002 commented
Mudanças requisitadas foram feitas, então estou aprovando esse PR!

2019-05-18 00:54 UTC, merged